# Configuration for the UI Toolkit
# Set the full class name of the factory you want to use.
# To switch to Mac, change this to: abstract_factory.factories.MacFactory
factory_class=abstract_factory.factories.WindowsFactory
